name: adc-toolbox
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip>=21.3.1
  - pip:
    - -r requirements.txt
  - anaconda
  - conda:
    - cartopy==0.19.0.post1
    - netCDF4==1.5.6
    - Pillow
    - matplotlib
    - scikit-learn